### PR TITLE
fix: update black to fix issue with click

### PR DESCRIPTION
**Pull request by c0state**
Should fix https://github.com/4Catalyzer/fourmat/issues/38

### CODE REVIEW

**Review by AaronBuxbaum — APPROVED** [review]

**Comment by c0state** [comment]
@sloria , can you build when you get a sec if this looks good? Thanks!

**Review by sloria — APPROVED** [review]

**Comment by sloria** [comment]
@c0state i release 0.11.1 with this fix. btw, what's your pypi username? i'll give you access to publish

**Comment by c0state** [comment]
> @c0state i release 0.11.1 with this fix. btw, what's your pypi username? i'll give you access to publish

Can you add `stephen.liu`? Thanks!

**Comment by sloria** [comment]
Ah unfortunately I don't have admin privs on the repo. @itajaja can you add `stephen.liu` and `sloria` as `Owner`s on https://pypi.org/manage/project/fourmat/collaboration/ ? 🙏

**Pull request merged**
