### PR TITLE
fix: Do not create pyproject.toml/.flake8 when running fourmat in a project subdirectory

### PR DESCRIPTION
**Pull request by ccarpita**

### CODE REVIEW

**Review by itajaja — APPROVED** [review]
shouldn't be for the .flake8 file too?

**Comment by ccarpita** [comment]
@itajaja Do you mean that it should consider project root to be wherever `.flake8` is? I think that's reasonable, but I'm wondering if we can accept an environmental variable for this as well (`FOURMAT_PROJECT_DIR`, say). What do you think?

**Comment by itajaja** [comment]
no, sorry, I misread your pr. the change of PR title explained it, i reread the code, all good :)

**Comment by ccarpita** [comment]
@itajaja I'd like to write some pytests for Project root detection before merging...we should get some Github Action CI going for this too, but maybe after merging :)

**Comment by itajaja** [comment]
yes! the old travis stuff stopped working :)

**Comment by itajaja** [comment]
since there are no tests at all, I'd rather merge this pr as is before adding the test infra, but up to you

**Comment by ccarpita** [comment]
@itajaja I went ahead and added tests, verified that they pass, and also did an editable install and tested the end-to-end behavior with fourmat in a subdirectory of our software repository. I am now comfortable merging

**Comment by robert914** [comment]
@ccarpita Did you by chance test this from within a submodule within that software repository?

**Comment by ccarpita** [comment]
@robert914 Yes, I tested the above behavior within a subdirectory of software, and it did not generate pyproject.toml files or mis-fourmat things

**Review by itajaja — APPROVED** [review]
nice

**Comment by itajaja** [comment]
https://pypi.org/project/fourmat/0.10.0/

**Comment by jquense** [comment]
Getting complaints in docker images that `.fourmat` doesn't exist at `/` even when the pwd is something else. Seems like a bug @ccarpita

**Comment by ccarpita** [comment]
@jquense I made a PR to fix the issue you're describing: https://github.com/4Catalyzer/fourmat/pull/34

**Pull request merged**
